// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsO5eS2pCTgU_Nx9Jpn0meZzrgDSkgOA',
    appId: '1:763413463427:web:ba851faf30aa1262e2f6b6',
    messagingSenderId: '763413463427',
    projectId: 'pathsaathi-bee16',
    authDomain: 'pathsaathi-bee16.firebaseapp.com',
    storageBucket: 'pathsaathi-bee16.firebasestorage.app',
    measurementId: 'G-V4M1PTHDNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClCYywRGf8w1q6VTucr1UTQ-tYmqZHSeE',
    appId: '1:763413463427:android:38af5a9e339072d2e2f6b6',
    messagingSenderId: '763413463427',
    projectId: 'pathsaathi-bee16',
    storageBucket: 'pathsaathi-bee16.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcsO5eS2pCTgU_Nx9Jpn0meZzrgDSkgOA',
    appId: '1:763413463427:web:c35c6f291dbba318e2f6b6',
    messagingSenderId: '763413463427',
    projectId: 'pathsaathi-bee16',
    authDomain: 'pathsaathi-bee16.firebaseapp.com',
    storageBucket: 'pathsaathi-bee16.firebasestorage.app',
    measurementId: 'G-32572SDWZ5',
  );
}
